import React, { createContext, useContext, useEffect, useState } from 'react';

// Language dictionary for translation
const LANGS: Record<string, Record<string, string>> = {  en: {
    home: 'Home',
    orders: 'Orders',
    pos: 'POS',
    receipts: 'Receipts',
    settings: 'Settings',
    dashboard: 'Dashboard',
    management: 'Management',
    system: 'Point of Sale System',
    loading: 'Loading...',
    total: 'Total',
    pending: 'Pending',
    delivered: 'Delivered',
    search: 'Search',
    filter: 'Filter',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delivery: 'Delivery',
    customer: 'Customer',
    payment: 'Payment',
    username: 'Username',
    email: 'Email',
    role: 'Role',
    branch: 'Branch',
    cashier: 'Cashier',
    profile: 'Profile Information',
    theme: 'Theme',
    language: 'Language',
    notifications: 'Notifications',
    printer: 'Printer Settings',
    logout: 'Log out',
    // Home page translations
    welcomeToSteakz: 'Welcome to STEAKZ',
    exquisiteDining: 'Exquisite Dining Experience',
    welcomeSubtext: 'Discover exceptional flavors and unforgettable moments at our premium restaurant',
    viewMenu: 'View Menu',
    findLocation: 'Find Location',
    aboutRestaurant: 'About Our Restaurant',
    aboutText: 'At STEAKZ Restaurant, we pride ourselves on serving exceptional cuisine crafted from the finest ingredients. Our passionate chefs create memorable dining experiences that bring people together.',
    featuredDishes: 'Featured Dishes',
    viewFullMenu: 'View Full Menu',
    customerReviews: 'Customer Reviews',    // Menu page translations
    ourMenu: 'Our Menu',
    menuSubtext: 'Discover our delicious selection of dishes crafted with the finest ingredients',
    category: 'Category',
    allCategories: 'All Categories',
    searchDishes: 'Search dishes...',
    addToCart: 'Add to Cart',
    viewCart: 'View Cart',
    available: 'Available',
    unavailable: 'Unavailable',
    errorLoadingMenu: 'Error loading menu',
    shoppingCart: 'Shopping Cart',
    yourCartIsEmpty: 'Your cart is empty',
    selectPaymentMethod: 'Select payment method',
    cash: 'Cash',
    creditCard: 'Credit Card',
    debitCard: 'Debit Card',
    mobilePayment: 'Mobile Payment',    placeOrder: 'Place Order',
    placingOrder: 'Placing order...',    // NotFound page translations
    pageNotFound: 'Page Not Found',
    pageNotFoundDesc: 'Sorry, the page you are looking for does not exist or has been moved.',
    backToHome: 'Back to Home',
    // Login page translations
    login: 'Login',
    loginDesc: 'Welcome back! Please enter your details.',
    emailOrUsername: 'Email or Username',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign in',
    orContinueWith: 'Or continue with',
    google: 'Google',
    apple: 'Apple',
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign up',
    backToWebsite: 'Back to website',
    welcomeTo: 'Welcome to',
    brand: 'STEAKZ',
    capturingMoments: 'Capturing Moments,',
    creatingMemories: 'Creating Memories',
    loginFailed: 'Login failed',
    // Orders page translations
    restaurantOrders: 'Restaurant Orders',
    ordersSubtitle: 'Monitor and manage all customer orders in real-time',
    searchPlaceholder: 'Search by order ID or customer...',
    allOrders: 'All Orders',
    preparing: 'Preparing',
    ready: 'Ready',
    cancelled: 'Cancelled',
    orderNumber: 'Order',
    items: 'Items',
    status: 'Status',
    deliveryAddress: 'Delivery Address',
    orderTime: 'Order Time',
    paymentMethod: 'Payment',
    noOrders: 'No orders found',
    noOrdersDesc: 'Orders will appear here as customers place them.',
    loadingOrders: 'Loading orders...',
    errorLoading: 'Error loading orders',    viewDetails: 'View Details',
    updateStatus: 'Update Status',
    // MyOrders page translations
    myOrdersTitle: 'My Orders',
    myOrdersSubtitle: 'Track your order history and current deliveries',
    orderedAt: 'Ordered',
    noOrdersYet: 'No orders yet',
    noOrdersYetDesc: 'You haven\'t placed any orders yet.',
    browseMenu: 'Browse our menu to place your first order!',
    loginRequired: 'You must be logged in as a customer to view orders.',    trackOrder: 'Track Order',
    reorder: 'Order Again',
    // CreatePost page translations
    createPost: 'Create Post',
    title: 'Title',
    content: 'Content',    creating: 'Creating...',
    failedToCreatePost: 'Failed to create post',
    // Footer translations
    openingHours: 'Opening Hours',
    mondayFriday: 'Monday - Friday: 11:00 AM - 11:00 PM',
    saturdaySunday: 'Saturday - Sunday: 10:00 AM - 12:00 AM',
    contact: 'Contact',
    location: 'Location',    allRightsReserved: '© 2024 STEAKZ Restaurant. All rights reserved.',
    mainLocation: 'STEAKZ Main Location',
    // Locations section translations
    visitOurLocations: 'Visit Our Locations',
    findNearestRestaurant: 'Find your nearest STEAKZ Restaurant and make a reservation today.',
    findLocations: 'Find Locations',    // Branches page translations
    ourBranches: 'Our Branches',
    branchesSubtext: 'Find the branch nearest to you. Click on the map icon to see the location on Google Maps.',
    address: 'Address',
    phone: 'Phone',
    manager: 'Manager',
    viewOnMap: 'View on map',
    call: 'Call',
    // Inventory page translations
    inventory: 'Inventory',
    inventoryDescription: 'Manage and monitor stock levels for all ingredients and supplies',
    loadingInventory: 'Loading inventory...',
    allItems: 'All Items',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    item: 'Item',
    quantity: 'Quantity',
    lastUpdated: 'Last Updated',
    noInventoryItems: 'No inventory items found',
    noLowStockItems: 'No low stock items',
    noOutOfStockItems: 'No out of stock items',
    menuItems: 'Menu Items',
    preferences: 'Preferences'
  },
  es: {
    home: 'Inicio',
    orders: 'Pedidos',
    pos: 'TPV',
    receipts: 'Recibos',
    settings: 'Configuración',
    dashboard: 'Panel',
    management: 'Gestión',
    system: 'Sistema de Punto de Venta',
    loading: 'Cargando...',
    total: 'Total',
    pending: 'Pendiente',
    delivered: 'Entregado',
    search: 'Buscar',
    filter: 'Filtrar',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    delivery: 'Entrega',
    customer: 'Cliente',
    payment: 'Pago',
    username: 'Usuario',
    email: 'Correo',
    role: 'Rol',
    branch: 'Sucursal',
    cashier: 'Cajero',
    profile: 'Información de Perfil',
    theme: 'Tema',
    language: 'Idioma',
    notifications: 'Notificaciones',
    printer: 'Ajustes de Impresora',
    logout: 'Cerrar sesión'
  },
  fr: {
    home: 'Accueil',
    orders: 'Commandes',
    pos: 'PDV',
    receipts: 'Reçus',
    settings: 'Paramètres',
    dashboard: 'Tableau de bord',
    management: 'Gestion',
    system: 'Système Point de Vente',
    loading: 'Chargement...',
    total: 'Total',
    pending: 'En attente',
    delivered: 'Livré',
    search: 'Rechercher',
    filter: 'Filtrer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    delivery: 'Livraison',
    customer: 'Client',
    payment: 'Paiement',
    username: 'Nom d\'utilisateur',
    email: 'Email',
    role: 'Rôle',
    branch: 'Branche',
    cashier: 'Caissier',
    profile: 'Informations du Profil',
    theme: 'Thème',
    language: 'Langue',
    notifications: 'Notifications',
    printer: 'Paramètres Imprimante',
    logout: 'Se déconnecter'
  },
  de: {
    home: 'Startseite',
    orders: 'Bestellungen',
    pos: 'Kasse',
    receipts: 'Belege',
    settings: 'Einstellungen',
    dashboard: 'Dashboard',
    management: 'Verwaltung',
    system: 'Kassensystem',
    loading: 'Laden...',
    total: 'Gesamt',
    pending: 'Ausstehend',
    delivered: 'Geliefert',
    search: 'Suchen',
    filter: 'Filtern',
    save: 'Speichern',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    delivery: 'Lieferung',
    customer: 'Kunde',
    payment: 'Zahlung',
    username: 'Benutzername',
    email: 'E-Mail',
    role: 'Rolle',
    branch: 'Filiale',
    cashier: 'Kassierer',
    profile: 'Profilinformationen',
    theme: 'Thema',
    language: 'Sprache',
    notifications: 'Benachrichtigungen',    printer: 'Druckereinstellungen',
    logout: 'Abmelden'
  },
  sv: {
    home: 'Hem',
    orders: 'Beställningar',
    pos: 'Kassa',
    receipts: 'Kvitton',
    settings: 'Inställningar',
    dashboard: 'Instrumentpanel',
    management: 'Hantering',
    system: 'Kassasystem',
    loading: 'Laddar...',
    total: 'Totalt',
    pending: 'Väntande',
    delivered: 'Levererat',
    search: 'Sök',
    filter: 'Filtrera',
    save: 'Spara',
    cancel: 'Avbryt',
    confirm: 'Bekräfta',
    delivery: 'Leverans',
    customer: 'Kund',
    payment: 'Betalning',
    username: 'Användarnamn',
    email: 'E-post',
    role: 'Roll',
    branch: 'Filial',
    cashier: 'Kassör',
    profile: 'Profilinformation',
    theme: 'Tema',
    language: 'Språk',    notifications: 'Notiser',
    printer: 'Skrivarinställningar',
    logout: 'Logga ut',
    // Home page translations
    welcomeToSteakz: 'Välkommen till STEAKZ',
    exquisiteDining: 'Utsökt Matupplevelse',
    welcomeSubtext: 'Upptäck exceptionella smaker och oförglömliga stunder på vår premiumrestaurang',
    viewMenu: 'Visa Meny',
    findLocation: 'Hitta Plats',
    aboutRestaurant: 'Om Vår Restaurang',
    aboutText: 'På STEAKZ Restaurant är vi stolta över att servera exceptionell mat gjord av de finaste ingredienserna. Våra passionerade kockar skapar minnesvärda matupplevelser som för människor samman.',
    featuredDishes: 'Utvalda Rätter',
    viewFullMenu: 'Visa Hela Menyn',
    customerReviews: 'Kundrecensioner',    // Menu page translations
    ourMenu: 'Vår Meny',
    menuSubtext: 'Upptäck vårt läckra urval av rätter tillagade med de finaste ingredienserna',
    category: 'Kategori',
    allCategories: 'Alla Kategorier',
    searchDishes: 'Sök rätter...',
    addToCart: 'Lägg till i Kundvagn',
    viewCart: 'Visa Kundvagn',
    available: 'Tillgänglig',
    unavailable: 'Ej tillgänglig',
    errorLoadingMenu: 'Fel vid laddning av meny',
    shoppingCart: 'Kundvagn',
    yourCartIsEmpty: 'Din kundvagn är tom',
    selectPaymentMethod: 'Välj betalningsmetod',
    cash: 'Kontanter',
    creditCard: 'Kreditkort',
    debitCard: 'Betalkort',
    mobilePayment: 'Mobilbetalning',    placeOrder: 'Lägg Beställning',
    placingOrder: 'Lägger beställning...',    // NotFound page translations
    pageNotFound: 'Sidan Hittades Inte',
    pageNotFoundDesc: 'Tyvärr, sidan du letar efter finns inte eller har flyttats.',
    backToHome: 'Tillbaka Till Hem',
    // Login page translations
    login: 'Logga in',
    loginDesc: 'Välkommen tillbaka! Vänligen ange dina uppgifter.',
    emailOrUsername: 'E-post eller användarnamn',
    password: 'Lösenord',
    forgotPassword: 'Glömt lösenord?',
    signIn: 'Logga in',
    orContinueWith: 'Eller fortsätt med',
    google: 'Google',
    apple: 'Apple',
    dontHaveAccount: 'Har du inget konto?',
    signUp: 'Registrera dig',
    backToWebsite: 'Tillbaka till webbplats',
    welcomeTo: 'Välkommen till',
    brand: 'STEAKZ',
    capturingMoments: 'Fånga ögonblick,',
    creatingMemories: 'Skapa minnen',
    loginFailed: 'Inloggning misslyckades',
    // Orders page translations
    restaurantOrders: 'Restaurangbeställningar',
    ordersSubtitle: 'Övervaka och hantera alla kundbeställningar i realtid',
    searchPlaceholder: 'Sök efter order-ID eller kund...',
    allOrders: 'Alla Beställningar',
    preparing: 'Förbereder',
    ready: 'Klar',
    cancelled: 'Avbruten',
    orderNumber: 'Beställning',
    items: 'Varor',
    status: 'Status',
    deliveryAddress: 'Leveransadress',
    orderTime: 'Beställningstid',
    paymentMethod: 'Betalning',
    noOrders: 'Inga beställningar hittades',
    noOrdersDesc: 'Beställningar kommer att visas här när kunder lägger dem.',
    loadingOrders: 'Laddar beställningar...',
    errorLoading: 'Fel vid laddning av beställningar',    viewDetails: 'Visa Detaljer',
    updateStatus: 'Uppdatera Status',
    // MyOrders page translations
    myOrdersTitle: 'Mina Beställningar',
    myOrdersSubtitle: 'Spåra din beställningshistorik och aktuella leveranser',
    orderedAt: 'Beställd',
    noOrdersYet: 'Inga beställningar än',
    noOrdersYetDesc: 'Du har inte lagt några beställningar än.',
    browseMenu: 'Bläddra i vår meny för att lägga din första beställning!',
    loginRequired: 'Du måste vara inloggad som kund för att se beställningar.',    trackOrder: 'Spåra Beställning',
    reorder: 'Beställ Igen',
    // CreatePost page translations
    createPost: 'Skapa Inlägg',
    title: 'Titel',
    content: 'Innehåll',    creating: 'Skapar...',
    failedToCreatePost: 'Misslyckades att skapa inlägg',
    // Footer translations
    openingHours: 'Öppettider',
    mondayFriday: 'Måndag - Fredag: 11:00 - 23:00',
    saturdaySunday: 'Lördag - Söndag: 10:00 - 00:00',
    contact: 'Kontakt',
    location: 'Plats',    allRightsReserved: '© 2024 STEAKZ Restaurant. Alla rättigheter förbehållna.',
    mainLocation: 'STEAKZ Huvudkontor',
    // Locations section translations
    visitOurLocations: 'Besök Våra Restauranger',
    findNearestRestaurant: 'Hitta din närmaste STEAKZ Restaurant och boka ett bord idag.',
    findLocations: 'Hitta Restauranger',    // Branches page translations
    ourBranches: 'Våra Filialer',
    branchesSubtext: 'Hitta filialen närmast dig. Klicka på kartikonen för att se platsen på Google Maps.',
    address: 'Adress',
    phone: 'Telefon',
    manager: 'Chef',
    viewOnMap: 'Visa på karta',
    call: 'Ring',
    // Inventory page translations
    inventory: 'Lager',
    inventoryDescription: 'Hantera och övervaka lagernivåer för alla ingredienser och förnödenheter',
    loadingInventory: 'Laddar lager...',
    allItems: 'Alla Artiklar',
    lowStock: 'Lågt Lager',
    outOfStock: 'Slut i Lager',
    inStock: 'I Lager',
    item: 'Artikel',
    quantity: 'Mängd',
    lastUpdated: 'Senast Uppdaterad',
    noInventoryItems: 'Inga lagerartiklar hittades',
    noLowStockItems: 'Inga artiklar med lågt lager',
    noOutOfStockItems: 'Inga slutsålda artiklar',
    menuItems: 'Menyartiklar',
    preferences: 'Inställningar'
  }
};

export interface Settings {
  theme: 'light' | 'dark';
  language: string;
  currency: string;
  notifications: boolean;
  autoLogout: number;
  printerSettings: {
    defaultPrinter: string;
    copies: number;
    paperSize: string;
  };
}

const defaultSettings: Settings = {
  theme: (localStorage.getItem('theme') as 'light' | 'dark') || 'light',
  language: localStorage.getItem('language') || 'en',
  currency: localStorage.getItem('currency') || 'EUR',
  notifications: localStorage.getItem('notifications') !== 'false',
  autoLogout: parseInt(localStorage.getItem('autoLogout') || '30'),
  printerSettings: JSON.parse(localStorage.getItem('printerSettings') || '{"defaultPrinter":"Receipt Printer 01","copies":1,"paperSize":"A4"}')
};

export const SettingsContext = createContext<{
  settings: Settings;
  setSettings: React.Dispatch<React.SetStateAction<Settings>>;
  t: (key: string) => string;
} | undefined>(undefined);

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [settings, setSettings] = useState<Settings>(defaultSettings);

  const t = (key: string) => LANGS[settings.language]?.[key] || key;
  useEffect(() => {
    document.body.className = settings.theme;
    localStorage.setItem('theme', settings.theme);
    localStorage.setItem('language', settings.language);
    localStorage.setItem('currency', settings.currency);
    localStorage.setItem('notifications', settings.notifications.toString());
    localStorage.setItem('autoLogout', settings.autoLogout.toString());
    localStorage.setItem('printerSettings', JSON.stringify(settings.printerSettings));
  }, [settings]);

  return (
    <SettingsContext.Provider value={{ settings, setSettings, t }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const ctx = useContext(SettingsContext);
  if (!ctx) throw new Error('useSettings must be used within SettingsProvider');
  return ctx;
};
